export const ASYNC_PROTOCOL_VERSION = 1;
export const STORAGE_PROTOCOL_VERSION = 2;

export const ASYNC_BOUNDARY_ARM_MIN = 0;
export const ASYNC_BOUNDARY_ARM_PENDING = 1;
export const ASYNC_BOUNDARY_ARM_MAX = 2;
