import { defineConfig } from 'vite-plus';

export default defineConfig({
	staged: {
		'*': 'vp check --fix',
	},
	pack: {
		deps: {
			neverBundle: ['rolldown', 'vite', 'vitest', 'vitest/browser'],
		},
		entry: {
			'serializer/index': './packages/serializer/src/index.ts',
			'compiler/index': './packages/compiler/src/index.ts',
			'runtime/index': './packages/runtime/src/index.ts',
			'runtime/graph': './packages/runtime/src/graph.ts',
			'web/dom-journal': './packages/web/src/dom-journal.ts',
			'web/dom-update': './packages/web/src/dom-update.ts',
			'web/event-only-resume': './packages/web/src/event-only-resume.ts',
			'web/event-resume': './packages/web/src/event-resume.ts',
			'web/index': './packages/web/src/index.ts',
			'web/render': './packages/web/src/render.ts',
			'web/render-to-string': './packages/web/src/render-to-string.ts',
			'web/resume': './packages/web/src/payload.ts',
			'bundler/rolldown': './packages/bundler/src/rolldown.ts',
			'bundler/vite': './packages/bundler/src/vite/index.ts',
			'router/index': './packages/router/src/index.ts',
			'router/vite': './packages/router/src/vite/index.ts',
			'router/vite/route-href': './packages/router/src/vite/entries/route-href.ts',
			'router/vite/runtime/create-route-discovery':
				'./packages/router/src/vite/runtime/create-route-discovery.ts',
			'router/vite/runtime/create-server-entry':
				'./packages/router/src/vite/runtime/create-server-entry.ts',
			'router/typescript-plugin': './packages/router/src/typescript-plugin/index.ts',
			'cli/index': './packages/cli/src/index.ts',
			'core/index': './packages/core/src/index.ts',
			'core/rolldown': './packages/core/src/rolldown.ts',
			'core/runtime': './packages/core/src/runtime.ts',
			'core/runtime/dom-journal': './packages/core/src/runtime/dom-journal.ts',
			'core/runtime/dom-update': './packages/core/src/runtime/dom-update.ts',
			'core/runtime/event-only-resume': './packages/core/src/runtime/event-only-resume.ts',
			'core/runtime/event-resume': './packages/core/src/runtime/event-resume.ts',
			'core/runtime/render': './packages/core/src/runtime/render.ts',
			'core/runtime/render-to-string': './packages/core/src/runtime/render-to-string.ts',
			'core/runtime/resume': './packages/core/src/runtime/resume.ts',
			'core/router': './packages/core/src/router.ts',
			'core/router/vite': './packages/core/src/router/vite.ts',
			'core/web': './packages/core/src/web.ts',
			'core/web/dom-journal': './packages/core/src/web/dom-journal.ts',
			'core/web/dom-update': './packages/core/src/web/dom-update.ts',
			'core/web/event-only-resume': './packages/core/src/web/event-only-resume.ts',
			'core/web/event-resume': './packages/core/src/web/event-resume.ts',
			'core/web/render': './packages/core/src/web/render.ts',
			'core/web/render-to-string': './packages/core/src/web/render-to-string.ts',
			'core/web/resume': './packages/core/src/web/resume.ts',
			'core/vite': './packages/core/src/vite.ts',
			'vitest-browser/index': './packages/vitest-browser/src/index.ts',
			'vitest-browser/vitest': './packages/vitest-browser/src/vitest.ts',
		},
		format: ['esm'],
		dts: true,
		clean: true,
	},
	test: {
		environment: 'node',
		include: ['packages/*/test/**/*.test.ts', 'scripts/**/*.test.ts'],
	},
	lint: {
		ignorePatterns: ['dist/**', 'node_modules/**'],
	},
	fmt: {
		useTabs: true,
		tabWidth: 4,
		printWidth: 100,
		endOfLine: 'lf',
		singleQuote: true,
		ignorePatterns: ['dist/**', 'node_modules/**'],
	},
});
