import type {
	BundlerPipelineTransformArtifact,
	BundlerTransformedModule,
} from '../../compiler/src/index.ts';
import { transformTsrxForBundler } from '../../compiler/src/index.ts';
import type { PipelineManifest, PipelineReceipt } from '../../protocol/src/index.ts';

export type ArcadeRolldownTransformResult = BundlerTransformedModule & {
	readonly moduleId: string;
	readonly artifact: BundlerPipelineTransformArtifact;
};

export type ArcadeRolldownPlugin = {
	readonly name: '@arcadejs/bundler/rolldown';
	readonly transform: (code: string, id: string) => Promise<ArcadeRolldownTransformResult | null>;
	readonly load: (id: string) => Promise<string | null>;
	readonly manifest: () => PipelineManifest;
	readonly receipts: () => ReadonlyArray<PipelineReceipt>;
	readonly artifactFor: (id: string) => BundlerPipelineTransformArtifact | undefined;
};

export function createArcadeRolldownPlugin(): ArcadeRolldownPlugin {
	const artifacts = new Map<string, BundlerPipelineTransformArtifact>();
	const virtualModules = new Map<string, string>();
	const receipts: PipelineReceipt[] = [];
	let currentManifest = emptyManifest();
	let revision = 0;

	return {
		name: '@arcadejs/bundler/rolldown',
		async transform(code, id) {
			if (!id.endsWith('.tsrx')) return null;

			revision++;
			const artifact = await transformTsrxForBundler({
				filename: id,
				source: code,
				revision,
			});
			artifacts.set(id, artifact);
			currentManifest = artifact.manifest;

			for (const module of artifact.virtualModules) {
				virtualModules.set(module.id, module.code);
			}

			receipts.push(...artifact.pipelineReceipts);
			receipts.push({
				stage: 'rolldown-transform',
				moduleId: id,
				inspectable: true,
				summary:
					'Rolldown POC plugin transformed a TSRX module through the compiler entry.',
				details: {
					virtualModuleIds: artifact.virtualModules.map((module) => module.id),
					emittedChunkIds: artifact.emittedChunks.map((chunk) => chunk.id),
					revision,
				},
			});

			return {
				...artifact.transformedModule,
				moduleId: id,
				artifact,
			};
		},
		async load(id) {
			const code = virtualModules.get(id);

			if (code === undefined) return null;

			receipts.push({
				stage: 'virtual-module-load',
				moduleId: id,
				inspectable: true,
				summary: 'Rolldown POC plugin served a virtual module generated by the transform.',
				details: {
					codeBytes: code.length,
				},
			});

			return code;
		},
		manifest() {
			return currentManifest;
		},
		receipts() {
			return [...receipts];
		},
		artifactFor(id) {
			return artifacts.get(id);
		},
	};
}

function emptyManifest(): PipelineManifest {
	return {
		protocol: 'arcade-pipeline-poc',
		revision: 0,
		transformedModules: [],
		virtualModules: [],
		emittedChunks: [],
		relationships: [],
	};
}
