// Writes the three files an agent or a crawler looks for before it reads any
// page: `robots.txt`, `sitemap.xml` and `llms.txt`. All three are generated from
// `nav.ts`, so adding a page to the sidebar is still the only thing an author
// does. Runs before `vp build`, which copies `public/` into the output.
//
// The site is one section of compiled.run, served under `/markless/`, so
// `public/` lands at `/markless/`. A host-level `/robots.txt` is the origin's to
// write; the copy here states this section's rules and points at its sitemap.
//
// Run: node --experimental-strip-types scripts/generate-seo.ts
import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { flatNav, nav, siteDescription, siteName, siteOrigin } from '../nav.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = resolve(root, 'public');
const base = `${siteOrigin}/markless`;
const sitemapUrl = `${base}/sitemap.xml`;

/** XML has five characters that cannot be written as themselves. */
const xmlText = (text: string) =>
	text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&apos;');

const absolute = (href: string) => `${siteOrigin}${href}`;

const robots = `# ${siteName} docs, served under /markless/ on ${siteOrigin}.
# The host's own /robots.txt governs the whole origin; this file states the
# rules for this section and names its sitemap.
# Generated by scripts/generate-seo.ts from nav.ts. Do not edit by hand.
User-agent: *
Allow: /markless/

Sitemap: ${sitemapUrl}
`;

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.ts from nav.ts. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${flatNav
	.map(
		(entry) =>
			`\t<url>\n\t\t<loc>${xmlText(absolute(entry.href))}</loc>\n\t\t<changefreq>weekly</changefreq>\n\t</url>`,
	)
	.join('\n')}
</urlset>
`;

const llms = `# ${siteName} docs

> ${siteDescription}

Generated by scripts/generate-seo.ts from nav.ts. Every page below is prose plus
runnable ${'`.tsrx`'} files, written against published @markless/* 0.3.1. Where something
on this site does not work on that version, the page says so out loud in a callout
rather than documenting the plan.

${nav
	.map(
		(section) =>
			`## ${section.title}\n\n${section.entries
				.map((entry) => `- [${entry.title}](${absolute(entry.href)}): ${entry.description ?? ''}`)
				.join('\n')}`,
	)
	.join('\n\n')}
`;

await writeFile(resolve(publicDir, 'robots.txt'), robots);
await writeFile(resolve(publicDir, 'sitemap.xml'), sitemap);
await writeFile(resolve(publicDir, 'llms.txt'), llms);
console.log(`generate-seo: robots.txt, sitemap.xml (${flatNav.length} urls) and llms.txt written`);
