import ts from 'typescript';
import { expect, test } from 'vitest';
import { buildRouteManifestFromFileIds } from '../src/route-manifest.ts';
import {
	createRouteTypesDeclaration,
	routeTypesEnvDeclaration,
	routeTypesEnvPath,
	routeTypesOutputPath,
} from '../src/route-types.ts';

test('creates Markless Router route type declarations from TSRX and MDX routes', () => {
	const manifest = buildRouteManifestFromFileIds([
		'/pages/index.tsrx',
		'/pages/about.tsrx',
		'/pages/blog/[slug].tsrx',
		'/pages/docs/[...slug].mdx',
		'/pages/404.tsrx',
	]);
	const declaration = createRouteTypesDeclaration(manifest);

	expect(routeTypesEnvPath).toBe('markless-router-env.d.ts');
	expect(routeTypesOutputPath).toBe('.output/markless/router/types/routes.d.ts');
	expect(routeTypesEnvDeclaration).toBe(
		'/// <reference path="./.output/markless/router/types/routes.d.ts" />\n',
	);
	expect(declaration).toContain('generated by Markless Router');
	expect(declaration).toContain('export type MarklessRouterStaticPageHref =');
	expect(declaration).toContain('| "/"');
	expect(declaration).toContain('| "/about"');
	expect(declaration).toContain('| `/blog/${string}`');
	expect(declaration).toContain('| "/blog/[slug]"');
	expect(declaration).toContain('| "/docs/[...slug]"');
	expect(declaration).toContain('export interface MarklessRouterRouteParams');
	expect(declaration).toContain('export type MarklessRouterLinkProps =');
	expect(declaration).toContain('interface MarklessRouterGeneratedRoutes');
	expect(declaration).not.toContain('TSX');
});

test('produces TypeScript route types that accept and reject expected values', () => {
	const manifest = buildRouteManifestFromFileIds([
		'/pages/index.tsrx',
		'/pages/about.tsrx',
		'/pages/blog/[slug].tsrx',
		'/pages/docs/[...slug].mdx',
	]);
	const routesFile = '/routes.d.ts';
	const testFile = '/test.ts';
	const sources = new Map([
		[routesFile, createRouteTypesDeclaration(manifest)],
		[
			testFile,
			[
				'import type { MarklessRouterConcretePageHref, MarklessRouterRouteParams, MarklessRouterRoutePattern } from "./routes";',
				'const home: MarklessRouterConcretePageHref = "/";',
				'const blog: MarklessRouterConcretePageHref = "/blog/hello";',
				'const docs: MarklessRouterConcretePageHref = "/docs/guides/getting-started";',
				'// @ts-expect-error unknown concrete route',
				'const missing: MarklessRouterConcretePageHref = "/missing";',
				'const blogPattern: MarklessRouterRoutePattern = "/blog/[slug]";',
				'// @ts-expect-error static routes are not route patterns',
				'const aboutPattern: MarklessRouterRoutePattern = "/about";',
				'const blogParams: MarklessRouterRouteParams["/blog/[slug]"] = { slug: "hello" };',
				'const docsParams: MarklessRouterRouteParams["/docs/[...slug]"] = { slug: ["guides", "intro"] };',
				'// @ts-expect-error wrong dynamic param name',
				'const badBlogParams: MarklessRouterRouteParams["/blog/[slug]"] = { id: "hello" };',
				'void home; void blog; void docs; void missing; void blogPattern; void aboutPattern; void blogParams; void docsParams; void badBlogParams;',
			].join('\n'),
		],
	]);
	const program = ts.createProgram(
		[testFile],
		{
			module: ts.ModuleKind.ESNext,
			moduleResolution: ts.ModuleResolutionKind.Bundler,
			noEmit: true,
			skipLibCheck: true,
			strict: true,
			target: ts.ScriptTarget.ES2023,
		},
		createMemoryCompilerHost(sources),
	);

	expect(
		ts
			.getPreEmitDiagnostics(program)
			.map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')),
	).toEqual([]);
});

function createMemoryCompilerHost(sources: ReadonlyMap<string, string>) {
	const host = ts.createCompilerHost({});
	const originalFileExists = host.fileExists.bind(host);
	const originalReadFile = host.readFile.bind(host);
	const originalGetSourceFile = host.getSourceFile.bind(host);

	host.fileExists = (fileName) => sources.has(fileName) || originalFileExists(fileName);
	host.readFile = (fileName) => sources.get(fileName) ?? originalReadFile(fileName);
	host.getSourceFile = (fileName, languageVersion, onError, shouldCreateNewSourceFile) => {
		const source = sources.get(fileName);
		if (source !== undefined) {
			return ts.createSourceFile(fileName, source, languageVersion);
		}

		return originalGetSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile);
	};

	return host;
}
