export {
	RadioGroupDescription as description,
	RadioGroupError as error,
	RadioGroupField as field,
	RadioGroupItem as item,
	RadioGroupItemField as itemfield,
	RadioGroupItemIndicator as itemindicator,
	RadioGroupItemLabel as itemlabel,
	RadioGroupItemTrigger as itemtrigger,
	RadioGroupLabel as label,
	RadioGroupRoot as root,
	radiogroupItemState,
	// One option's instance, for a consumer whose own part sits inside an item.
	radiogroupItemState as itemstate,
	radiogroupState,
	radiogroupState as state,
} from './radio-group.tsrx';
export type {
	RadioGroupDescriptionProps,
	RadioGroupErrorProps,
	RadioGroupFieldProps,
	RadioGroupItemFieldProps,
	RadioGroupItemIndicatorProps,
	RadioGroupItemLabelProps,
	RadioGroupItemProps,
	RadioGroupItemTriggerProps,
	RadioGroupLabelProps,
	RadioGroupOrientation,
	RadioGroupRootProps,
} from './radio-group-types.ts';
