import type { RouteManifest, RouteManifestRoute } from './route-manifest.ts';

export const routeTypesEnvPath = 'markless-router-env.d.ts';
export const routeTypesOutputPath = '.markless/router/types/routes.d.ts';
export const routeTypesEnvDeclaration =
	'/// <reference path="./.markless/router/types/routes.d.ts" />\n';

export function createRouteTypesDeclaration(manifest: RouteManifest): string {
	const routes = manifest.routes;
	const staticHrefs = routes
		.filter((route) => route.params.length === 0)
		.map((route) => stringLiteral(route.pathname));
	const routePatterns = routes
		.filter((route) => route.params.length > 0)
		.map((route) => stringLiteral(route.pattern));

	return [
		'/* This file is generated by Markless Router. Do not edit. */',
		'',
		createUnion('MarklessRouterStaticPageHref', staticHrefs),
		'',
		createUnion(
			'MarklessRouterConcretePageHref',
			routes.map((route) => hrefType(route)),
		),
		'',
		createUnion('MarklessRouterRoutePattern', routePatterns),
		'',
		createRouteParamsInterface(routes),
		'',
		createUnion('MarklessRouterExternalHref', [
			'`http://${string}`',
			'`https://${string}`',
			'`mailto:${string}`',
			'`tel:${string}`',
			'`#${string}`',
			'`?${string}`',
		]),
		'',
		'export type MarklessRouterAssetHref = `/${string}.${string}`;',
		'',
		createLinkTypes(),
		'',
	].join('\n');
}

function createUnion(name: string, members: readonly string[]): string {
	if (members.length === 0) {
		return `export type ${name} = never;`;
	}

	return [
		`export type ${name} =`,
		...members.map(
			(member, index) => `\t| ${member}${index === members.length - 1 ? ';' : ''}`,
		),
	].join('\n');
}

function createRouteParamsInterface(routes: readonly RouteManifestRoute[]): string {
	const dynamicRoutes = routes.filter((route) => route.params.length > 0);
	if (dynamicRoutes.length === 0) {
		return 'export interface MarklessRouterRouteParams {}';
	}

	return [
		'export interface MarklessRouterRouteParams {',
		...dynamicRoutes.flatMap((route) => [
			`\t${stringLiteral(route.pattern)}: {`,
			...route.params.map((param) => `\t\treadonly ${param.name}: ${paramType(param.kind)};`),
			'\t};',
		]),
		'}',
	].join('\n');
}

function hrefType(route: RouteManifestRoute): string {
	if (route.params.length === 0) {
		return stringLiteral(route.pathname);
	}

	return templateLiteralHref(route.pathname);
}

function templateLiteralHref(pathname: string): string {
	const segments = splitPathname(pathname).map((segment) => {
		if (segment === '**' || segment.startsWith(':')) {
			return '${string}';
		}

		return segment;
	});

	return `\`/${segments.join('/')}\``;
}

function splitPathname(pathname: string): string[] {
	return pathname === '/' ? [] : pathname.slice(1).split('/');
}

function paramType(kind: RouteManifestRoute['params'][number]['kind']): string {
	return kind === 'catch-all'
		? 'string | number | readonly (string | number)[]'
		: 'string | number';
}

function stringLiteral(value: string): string {
	return JSON.stringify(value);
}

function createLinkTypes(): string {
	return [
		'export type MarklessRouterRoutePatternLinkProps = {',
		'\t[Pattern in MarklessRouterRoutePattern]: {',
		'\t\treadonly href: Pattern;',
		'\t\treadonly params: MarklessRouterRouteParams[Pattern];',
		'\t};',
		'}[MarklessRouterRoutePattern];',
		'',
		'export type MarklessRouterConcreteLinkProps = {',
		'\treadonly href?: MarklessRouterStaticPageHref | MarklessRouterExternalHref | MarklessRouterAssetHref;',
		'\treadonly params?: never;',
		'};',
		'',
		'export type MarklessRouterNavigationProps = {',
		'\treadonly prefetch?: boolean | "intent" | "viewport";',
		'\treadonly replace?: boolean;',
		'\treadonly scroll?: boolean;',
		'};',
		'',
		'export type MarklessRouterLinkProps = MarklessRouterNavigationProps &',
		'\t(MarklessRouterConcreteLinkProps | MarklessRouterRoutePatternLinkProps);',
		'',
		'declare module "@markless/router" {',
		'\tinterface MarklessRouterGeneratedRoutes {',
		'\t\treadonly link: MarklessRouterLinkProps;',
		'\t}',
		'}',
	].join('\n');
}
