#!/usr/bin/env node
import { appendFileSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const validStatuses = ['pending', 'active', 'done', 'blocked'];
const statusOrder = ['active', 'blocked', 'pending'];
const fail = (message) => {
	console.error(`state-ledger: ${message}`);
	process.exitCode = 1;
};
const take = (args, name) => {
	const index = args.indexOf(name);
	if (index < 0) return undefined;
	const value = args[index + 1];
	if (!value || value.startsWith('--')) throw new Error(`${name} requires a value`);
	args.splice(index, 2);
	return value;
};
const takeAll = (args, name) => {
	const values = [];
	while (args.includes(name)) values.push(take(args, name));
	return values;
};
const readEvents = (file) => {
	let input;
	try {
		input = readFileSync(file, 'utf8');
	} catch (error) {
		if (error.code === 'ENOENT') return [];
		throw error;
	}
	const events = [];
	input.split('\n').forEach((line, index) => {
		if (!line.trim()) return;
		try {
			events.push(JSON.parse(line));
		} catch {
			console.error(`state-ledger: warning: skipped corrupt JSONL line ${index + 1}`);
		}
	});
	return events;
};
const currentEvents = (events) => {
	const latest = new Map();
	for (const event of events) latest.set(`${event.goal}\0${event.unit ?? ''}`, event);
	return statusOrder.flatMap((status) => [...latest.values()].filter((event) => event.status === status));
};
const label = (event) => `${event.goal}${event.unit ? `/${event.unit}` : ''}`;
const printable = (event) => `${event.ts} ${label(event)} ${event.status} ${event.summary}`;
const markdown = (value) => String(value).replaceAll('\\', '\\\\').replaceAll('|', '\\|').replaceAll('\n', ' ');

try {
	const args = process.argv.slice(2);
	const command = args.shift();
	const defaultRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
	const root = resolve(take(args, '--root') ?? defaultRoot);
	const ledger = resolve(root, 'specs/state.jsonl');
	if (command === 'append') {
		const goal = take(args, '--goal');
		const unit = take(args, '--unit');
		const status = take(args, '--status');
		const summary = take(args, '--summary');
		const refs = takeAll(args, '--ref');
		if (!goal?.trim() || !summary?.trim()) throw new Error('append requires non-empty --goal and --summary');
		if (!validStatuses.includes(status)) throw new Error(`invalid status: ${status ?? '(missing)'}`);
		if (args.length) throw new Error(`unknown argument: ${args[0]}`);
		const event = { ts: new Date().toISOString(), goal, unit: unit ?? null, status, summary, refs };
		appendFileSync(ledger, `${JSON.stringify(event)}\n`, 'utf8');
	} else if (command === 'status') {
		if (args.length) throw new Error(`unknown argument: ${args[0]}`);
		for (const event of currentEvents(readEvents(ledger))) console.log(`${label(event)} ${event.status} ${event.summary}`);
	} else if (command === 'tail') {
		const rawCount = take(args, '-n') ?? '10';
		if (args.length || !/^\d+$/.test(rawCount)) throw new Error('tail -n requires a non-negative integer');
		for (const event of readEvents(ledger).slice(-Number(rawCount))) console.log(printable(event));
	} else if (command === 'project') {
		if (args.length) throw new Error(`unknown argument: ${args[0]}`);
		const events = readEvents(ledger);
		const rows = currentEvents(events).map((event) => `| ${markdown(label(event))} | ${event.status} | ${markdown(event.summary)} |`);
		const recent = events.slice(-15).map((event) => `- ${markdown(printable(event))}`);
		const output = [
			'<!-- GENERATED by scripts/state-ledger.mjs - do not edit -->', '', '# Implementation State', '',
			'Legacy entries are preserved in [specs/state-archive.md](./state-archive.md).', '',
			'## Current Status', '', '| Goal / unit | Status | Summary |', '| --- | --- | --- |',
			...(rows.length ? rows : ['| _None_ |  |  |']), '', '## Recent Events', '',
			...(recent.length ? recent : ['- _None_']), ''
		].join('\n');
		writeFileSync(resolve(root, 'specs/state.md'), output, 'utf8');
	} else {
		throw new Error('usage: state-ledger <append|status|tail|project> [--root <dir>]');
	}
} catch (error) {
	fail(error.message);
}
