import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const cli = new URL('./state-ledger.mjs', import.meta.url).pathname;
const root = () => {
	const dir = mkdtempSync(join(tmpdir(), 'state-ledger-'));
	mkdirSync(join(dir, 'specs'));
	writeFileSync(join(dir, 'specs/state-archive.md'), '# Archive\n');
	return dir;
};
const run = (dir: string, ...args: string[]) =>
	execFileSync(process.execPath, [cli, ...args, '--root', dir], { encoding: 'utf8' });
const append = (dir: string, goal: string, status: string, summary: string, unit?: string) =>
	run(dir, 'append', '--goal', goal, ...(unit ? ['--unit', unit] : []), '--status', status, '--summary', summary);

describe('state ledger CLI', () => {
	it('appends a complete JSON event', () => {
		const dir = root();
		run(dir, 'append', '--goal', 'compiler', '--unit', 'u1', '--status', 'active', '--summary', 'First pass', '--ref', 'specs/a.md', '--ref', 'specs/b.md');
		const event = JSON.parse(readFileSync(join(dir, 'specs/state.jsonl'), 'utf8'));
		expect(event).toMatchObject({ goal: 'compiler', unit: 'u1', status: 'active', summary: 'First pass', refs: ['specs/a.md', 'specs/b.md'] });
		expect(new Date(event.ts).toISOString()).toBe(event.ts);
	});

	it('rejects an invalid status without appending', () => {
		const dir = root();
		writeFileSync(join(dir, 'specs/state.jsonl'), '{"existing":true}\n');
		const result = spawnSync(process.execPath, [cli, 'append', '--root', dir, '--goal', 'x', '--status', 'oops', '--summary', 'No']);
		expect(result.status).not.toBe(0);
		expect(readFileSync(join(dir, 'specs/state.jsonl'), 'utf8')).toBe('{"existing":true}\n');
	});

	it('uses the last event for each goal and unit', () => {
		const dir = root();
		append(dir, 'compiler', 'pending', 'Queued', 'u1');
		append(dir, 'compiler', 'active', 'Working', 'u1');
		expect(run(dir, 'status')).toBe('compiler/u1 active Working\n');
	});

	it('excludes done entries from status', () => {
		const dir = root();
		append(dir, 'done-goal', 'done', 'Finished');
		append(dir, 'waiting', 'blocked', 'Needs input');
		expect(run(dir, 'status')).toBe('waiting blocked Needs input\n');
	});

	it('projects deterministic markdown', () => {
		const dir = root();
		append(dir, 'compiler', 'active', 'Working');
		run(dir, 'project');
		const first = readFileSync(join(dir, 'specs/state.md'), 'utf8');
		run(dir, 'project');
		expect(readFileSync(join(dir, 'specs/state.md'), 'utf8')).toBe(first);
		expect(first).toContain('<!-- GENERATED by scripts/state-ledger.mjs - do not edit -->');
		expect(first).toContain('| compiler | active | Working |');
	});

	it('warns and skips corrupt JSONL lines', () => {
		const dir = root();
		writeFileSync(join(dir, 'specs/state.jsonl'), '{bad json}\n{"ts":"2026-01-01T00:00:00.000Z","goal":"ok","unit":null,"status":"pending","summary":"Valid","refs":[]}\n');
		const result = spawnSync(process.execPath, [cli, 'status', '--root', dir], { encoding: 'utf8' });
		expect(result.status).toBe(0);
		expect(result.stdout).toBe('ok pending Valid\n');
		expect(result.stderr).toContain('warning');
	});
});
